version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 301984890704.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=301984890704.dkr.ecr.ap-south-1.amazonaws.com/repo-ecr-cicd

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Docker image push completed.

artifacts:
  files:
    - '**/*'                # This ensures all folders/files (scripts, app.js, etc.)
  base-directory: .         # Ensure it picks everything from root
  discard-paths: no         # Preserve folder structure (scripts/ must remain intact)
